Sandgem_Town_Bottom_Left_House_MapScripts::
	.byte 0


Sandgem_Town_Bottom_Left_House_EventScript_Boy::
	msgbox Sandgem_Town_Bottom_Left_House_EventScript_Boy_Text, MSGBOX_NPC
	end


Sandgem_Town_Bottom_Left_House_EventScript_Girl::
	msgbox Sandgem_Town_Bottom_Left_House_EventScript_Girl_Text, MSGBOX_NPC
	end


Sandgem_Town_Bottom_Left_House_EventScript_Boy_Text::
	.string "Pokemon grwo steadily stronger from\n"
	.string "battling against other Pokemon.\p"
	.string "At first, you should take it easy,\n"
	.string "though.\p"
	.string "Heal your Pokemon regularly at Pokemon\n"
	.string "Centers while you're leveling them up.$"

Sandgem_Town_Bottom_Left_House_EventScript_Girl_Text::
	.string "A good trainer is one that takes care\n"
	.string "not to let their pokemon faint from\l"
	.string "losing HP.$"
