TwinLeafTownTopRightHouse_MapScripts::
	.byte 0


TwinLeafTownTopRightHouse_EventScript_Man::
# 5 "data/maps/TwinLeafTownTopRightHouse/scripts.pory"
	msgbox TwinLeafTownTopRightHouse_EventScript_Man_Text_0, MSGBOX_NPC
	end


TwinLeafTownTopRightHouse_EventScript_Man_Text_0:
# 5 "data/maps/TwinLeafTownTopRightHouse/scripts.pory"
	.string "You're off to hang with {RIVAL}\n"
	.string "again, right? You two sure are tight!$"
