VerityLakefront_MapScripts::
	.byte 0

VerityLakefront_EventScript_Sign::
	msgbox VerityLakefront_Text_Sign, MSGBOX_SIGN
	end

VerityLakefront_Text_Sign:
    .string "Lake Verity Ahead\p"
    .string "According to legend, this lake is home\n"
    .string "to the Pokemon said to be The Being of\l"
    .string "Emotion.\p"
    .string "It is because of this Pokemon that \n"
    .string "people can experience sorrow and joy.$"
