Twin_Leaf_Town_Bottom_Left_House_MapScripts::
	.byte 0


Twin_Leaf_Town_Bottom_Left_House_EventScript_Old_Lady::
	msgbox Twin_Leaf_Town_Bottom_Left_House_EventScript_Old_Lady_Text, MSGBOX_NPC
	end


TwinLeafTown_BottomLeft_House_EventScript_Little_Girl::
	msgbox TwinLeafTown_BottomLeft_House_EventScript_Little_Girl_Text, MSGBOX_NPC
	end


Twin_Leaf_Town_Bottom_Left_House_EventScript_Old_Lady_Text::
	.string "Did you hear?\p"
	.string "The Pokemon Professor returned\n"
	.string "to the next town over.\p"
	.string "They say he was gone for four long\n"
	.string "years.\p"
	.string "I wonder if he found some amazing\n"
	.string "Pokemon while he was gone?$"

TwinLeafTown_BottomLeft_House_EventScript_Little_Girl_Text::
	.string "Listen, listen, {PLAYER}.\p"
	.string "I want a cute Pokemon!$"
