#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_OLDALE_TOWN                  0x01
#define MAPSEC_DEWFORD_TOWN                 0x02
#define MAPSEC_LAVARIDGE_TOWN               0x03
#define MAPSEC_FALLARBOR_TOWN               0x04
#define MAPSEC_VERDANTURF_TOWN              0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_PETALBURG_CITY               0x07
#define MAPSEC_SLATEPORT_CITY               0x08
#define MAPSEC_MAUVILLE_CITY                0x09
#define MAPSEC_RUSTBORO_CITY                0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_LILYCOVE_CITY                0x0C
#define MAPSEC_MOSSDEEP_CITY                0x0D
#define MAPSEC_SOOTOPOLIS_CITY              0x0E
#define MAPSEC_EVER_GRANDE_CITY             0x0F
#define MAPSEC_ROUTE_101                    0x10
#define MAPSEC_ROUTE_102                    0x11
#define MAPSEC_ROUTE_103                    0x12
#define MAPSEC_ROUTE_104                    0x13
#define MAPSEC_ROUTE_105                    0x14
#define MAPSEC_ROUTE_106                    0x15
#define MAPSEC_ROUTE_107                    0x16
#define MAPSEC_ROUTE_108                    0x17
#define MAPSEC_ROUTE_109                    0x18
#define MAPSEC_ROUTE_110                    0x19
#define MAPSEC_ROUTE_111                    0x1A
#define MAPSEC_ROUTE_112                    0x1B
#define MAPSEC_ROUTE_113                    0x1C
#define MAPSEC_ROUTE_114                    0x1D
#define MAPSEC_ROUTE_115                    0x1E
#define MAPSEC_ROUTE_116                    0x1F
#define MAPSEC_ROUTE_117                    0x20
#define MAPSEC_ROUTE_118                    0x21
#define MAPSEC_ROUTE_119                    0x22
#define MAPSEC_ROUTE_120                    0x23
#define MAPSEC_ROUTE_121                    0x24
#define MAPSEC_ROUTE_122                    0x25
#define MAPSEC_ROUTE_123                    0x26
#define MAPSEC_ROUTE_124                    0x27
#define MAPSEC_ROUTE_125                    0x28
#define MAPSEC_ROUTE_126                    0x29
#define MAPSEC_ROUTE_127                    0x2A
#define MAPSEC_ROUTE_128                    0x2B
#define MAPSEC_ROUTE_129                    0x2C
#define MAPSEC_ROUTE_130                    0x2D
#define MAPSEC_ROUTE_131                    0x2E
#define MAPSEC_ROUTE_132                    0x2F
#define MAPSEC_ROUTE_133                    0x30
#define MAPSEC_ROUTE_134                    0x31
#define MAPSEC_UNDERWATER_124               0x32
#define MAPSEC_UNDERWATER_126               0x33
#define MAPSEC_UNDERWATER_127               0x34
#define MAPSEC_UNDERWATER_128               0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x36
#define MAPSEC_GRANITE_CAVE                 0x37
#define MAPSEC_MT_CHIMNEY                   0x38
#define MAPSEC_SAFARI_ZONE                  0x39
#define MAPSEC_BATTLE_FRONTIER              0x3A
#define MAPSEC_PETALBURG_WOODS              0x3B
#define MAPSEC_RUSTURF_TUNNEL               0x3C
#define MAPSEC_ABANDONED_SHIP               0x3D
#define MAPSEC_NEW_MAUVILLE                 0x3E
#define MAPSEC_METEOR_FALLS                 0x3F
#define MAPSEC_METEOR_FALLS2                0x40
#define MAPSEC_MT_PYRE                      0x41
#define MAPSEC_AQUA_HIDEOUT_OLD             0x42
#define MAPSEC_SHOAL_CAVE                   0x43
#define MAPSEC_SEAFLOOR_CAVERN              0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x45
#define MAPSEC_VICTORY_ROAD                 0x46
#define MAPSEC_MIRAGE_ISLAND                0x47
#define MAPSEC_CAVE_OF_ORIGIN               0x48
#define MAPSEC_SOUTHERN_ISLAND              0x49
#define MAPSEC_FIERY_PATH                   0x4A
#define MAPSEC_FIERY_PATH2                  0x4B
#define MAPSEC_JAGGED_PASS                  0x4C
#define MAPSEC_JAGGED_PASS2                 0x4D
#define MAPSEC_SEALED_CHAMBER               0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x4F
#define MAPSEC_SCORCHED_SLAB                0x50
#define MAPSEC_ISLAND_CAVE                  0x51
#define MAPSEC_DESERT_RUINS                 0x52
#define MAPSEC_ANCIENT_TOMB                 0x53
#define MAPSEC_INSIDE_OF_TRUCK              0x54
#define MAPSEC_SKY_PILLAR                   0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_AQUA_HIDEOUT                 0x58
#define MAPSEC_MAGMA_HIDEOUT                0x59
#define MAPSEC_MIRAGE_TOWER                 0x5A
#define MAPSEC_BIRTH_ISLAND                 0x5B
#define MAPSEC_FARAWAY_ISLAND               0x5C
#define MAPSEC_ARTISAN_CAVE                 0x5D
#define MAPSEC_MARINE_CAVE                  0x5E
#define MAPSEC_UNDERWATER_MARINE_CAVE       0x5F
#define MAPSEC_TERRA_CAVE                   0x60
#define MAPSEC_UNDERWATER_105               0x61
#define MAPSEC_UNDERWATER_125               0x62
#define MAPSEC_UNDERWATER_129               0x63
#define MAPSEC_DESERT_UNDERPASS             0x64
#define MAPSEC_ALTERING_CAVE                0x65
#define MAPSEC_NAVEL_ROCK                   0x66
#define MAPSEC_TRAINER_HILL                 0x67
#define MAPSEC_TWIN_LEAF_TOWN               0x68
#define MAPSEC_SANDGEM_TOWN                 0X69
#define MAPSEC_JUBILIFE_CITY                0X6A
#define MAPSEC_OREBURGH_CITY                0X6B
#define MAPSEC_FLOROMA_TOWN                 0X6C
#define MAPSEC_ETERNA_CITY                  0X6D
#define MAPSEC_HEARTHOME_CITY               0X6E
#define MAPSEC_SOLACEON_TOWN                0X70
#define MAPSEC_VEILSTONE_CITY               0X71
#define MAPSEC_PASTORIA_CITY                0X72
#define MAPSEC_CELESTIC_TOWN                0X73
#define MAPSEC_CANALAVE_CITY                0X74
#define MAPSEC_SUNYSHORE_CITY               0X75
#define MAPSEC_VALLEY_WINDWORKS             0X76
#define MAPSEC_FUEGO_IRONWORKS              0X77
#define MAPSEC_ETERNA_FOREST                0X78
#define MAPSEC_SINNOH_POKEMON_LEAUGE        0X79
#define MAPSEC_VERITY_LAKEFRONT            0X7A
#define MAPSEC_LAKE_VERITY                  0X7B
#define MAPSEC_VALOR_LAKEFRONT              0X7C
#define MAPSEC_ROUTE_201                    0X7D
#define MAPSEC_ROUTE_202                    0X7E
#define MAPSEC_ROUTE_203                    0X7F
#define MAPSEC_ROUTE_204                    0X80
#define MAPSEC_ROUTE_205                    0X81
#define MAPSEC_ROUTE_206                    0X82
#define MAPSEC_ROUTE_207                    0X83
#define MAPSEC_ROUTE_208                    0X84
#define MAPSEC_ROUTE_209                    0X85
#define MAPSEC_ROUTE_210                    0X86
#define MAPSEC_ROUTE_211                    0X87
#define MAPSEC_ROUTE_212                    0X88
#define MAPSEC_ROUTE_213                    0X89
#define MAPSEC_ROUTE_214                    0X8A
#define MAPSEC_ROUTE_215                    0X8B
#define MAPSEC_ROUTE_218                    0X8C
#define MAPSEC_ROUTE_219                    0X8D
#define MAPSEC_ROUTE_220                    0X8E
#define MAPSEC_ROUTE_221                    0X8F
#define MAPSEC_ROUTE_222                    0X90
#define MAPSEC_ROUTE_223                    0X91
#define MAPSEC_OREBURGH_GATE                0X92
#define MAPSEC_RAVAGED_PATH                 0X93
#define MAPSEC_NONE                         0x94

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#endif //GUARD_REGIONMAPSEC_H
