OreburghCityMiddleHouse_MapScripts::
	.byte 0


OreburghCityMiddleHouse_EventScript_Woman::
	msgbox OreburghCityMiddleHouse_EventScript_Woman_Text_0, MSGBOX_NPC
	end


OreburghCityMiddleHouse_EventScript_Hiker::
	msgbox OreburghCityMiddleHouse_EventScript_Hiker_Text_0, MSGBOX_NPC
	end


OreburghCityMiddleHouse_EventScript_Woman_Text_0:
	.string "Roark is a user of Rock-type Pokémon.\p"
	.string "Don't you think Rock-type Pokémon are\n"
	.string "nice? I like how lumpy they are!$"

OreburghCityMiddleHouse_EventScript_Hiker_Text_0:
	.string "Roark is our town's Gym Leader.\p"
	.string "He may be young, but he keeps the\n"
	.string "mine running safely and efficiently.$"
