JubilifeCitySouthHouse2F_MapScripts::
	.byte 0


JubilifeCitySouthHouse2F_EventScripts_Youngster::
	msgbox JubilifeCitySouthHouse2F_EventScripts_Youngster_Text_0, MSGBOX_NPC
	end


JubilifeCitySouthHouse2F_EventScripts_Woman::
	msgbox JubilifeCitySouthHouse2F_EventScripts_Woman_Text_0, MSGBOX_NPC
	end


JubilifeCitySouthHouse2F_EventScripts_Girl::
	msgbox JubilifeCitySouthHouse2F_EventScripts_Girl_Text_0, MSGBOX_NPC
	end


JubilifeCitySouthHouse2F_EventScripts_Youngster_Text_0:
	.string "Did you know?\p"
	.string "Some kinds of Pokémon evolve when\n"
	.string "they get stronger from battling!\p"
	.string "When they evolve, they can take on\n"
	.string "completely different forms!$"

JubilifeCitySouthHouse2F_EventScripts_Woman_Text_0:
	.string "Evolution makes Pokémon just that\n"
	.string "much more fascinating.\p"
	.string "The mysteries of evolution... Can that\n"
	.string "dandy Prof. Rowan unravel them?$"

JubilifeCitySouthHouse2F_EventScripts_Girl_Text_0:
	.string "Didn’t Prof. Rowan conduct research\n"
	.string "with Prof. Oak of the Kanto region?$"
