OreburghCityLeftBigHouse1F_MapScripts::
	.byte 0


OreburghCityLeftBigHouse1F_EventScript_Woman::
	msgbox OreburghCityLeftBigHouse1F_EventScript_Woman_Text_0, MSGBOX_NPC
	end


OreburghCityLeftBigHouse1F_EventScript_Boy::
	msgbox OreburghCityLeftBigHouse1F_EventScript_Boy_Text_0, MSGBOX_NPC
	end


OreburghCityLeftBigHouse1F_EventScript_Youngster::
	msgbox OreburghCityLeftBigHouse1F_EventScript_Youngster_Text_0, MSGBOX_NPC
	end


OreburghCityLeftBigHouse1F_EventScript_Books::
	msgbox OreburghCityLeftBigHouse1F_EventScript_Books_Text_0, MSGBOX_DEFAULT
	end


OreburghCityLeftBigHouse1F_EventScript_Woman_Text_0:
	.string "Roark lets us train our Pokémon in\n"
	.string "the mine.$"

OreburghCityLeftBigHouse1F_EventScript_Boy_Text_0:
	.string "There are eight Gym Leaders in the\n"
	.string "Sinnoh region.\p"
	.string "The objective for Trainers is to get\n"
	.string "Gym Badges from them all.\p"
	.string "That means you have to defeat all of\n"
	.string "them in battles at their Gyms!$"

OreburghCityLeftBigHouse1F_EventScript_Youngster_Text_0:
	.string "A Gym Leader isn't like just any Trainer\n"
	.string "you meet.\p"
	.string "Obviously, they're a lot tougher.\n"
	.string "A lot.\p"
	.string "I'd take as many Pokémon as possible\n"
	.string "if I were you.$"

OreburghCityLeftBigHouse1F_EventScript_Books_Text_0:
	.string "It's chock-full of Pokémon books and\n"
	.string "photo collections.$"
