OreburghCityLeftHouse_MapScripts::
	.byte 0


OreburghCityLeftHouse_EventScript_Woman::
	msgbox OreburghCityLeftHouse_EventScript_Woman_Text_0, MSGBOX_NPC
	end


OreburghCityLeftHouse_EventScript_Youngster::
	msgbox OreburghCityLeftHouse_EventScript_Youngster_Text_0, MSGBOX_NPC
	end


OreburghCityLeftHouse_EventScript_Pikachu::
	msgbox OreburghCityLeftHouse_EventScript_Pikachu_Text_0, MSGBOX_NPC
	end


OreburghCityLeftHouse_EventScript_Woman_Text_0:
	.string "You know how Pokémon have different\n"
	.string "natures like we have personalities?\p"
	.string "I don't think it's surprising to see\n"
	.string "Pokémon in different colors.$"

OreburghCityLeftHouse_EventScript_Youngster_Text_0:
	.string "Have you ever seen or heard about\n"
	.string "differently colored Pokémon?\p"
	.string "For instance, a regular Pikachu has\n"
	.string "a yellow body, correct?\p"
	.string "Well, the different-colored Pikachu\n"
	.string "has a sort of orange body.$"

OreburghCityLeftHouse_EventScript_Pikachu_Text_0:
	.string "PIKACHU: Pikaaah!$"
