TwinLeafTownBottomLeftHouse_MapScripts::
	.byte 0


TwinLeafTownBottomLeftHouse_EventScript_Old_Lady::
	msgbox TwinLeafTownBottomLeftHouse_EventScript_Old_Lady_Text_0, MSGBOX_NPC
	end


TwinLeafTownBottomLeftHouse_EventScript_Little_Girl::
	msgbox TwinLeafTownBottomLeftHouse_EventScript_Little_Girl_Text_0, MSGBOX_NPC
	end


TwinLeafTownBottomLeftHouse_EventScript_Old_Lady_Text_0:
	.string "Did you hear?\p"
	.string "The Pokémon Professor returned\n"
	.string "to the next town over.\p"
	.string "They say he was gone for four long\n"
	.string "years.\p"
	.string "I wonder if he found some amazing\n"
	.string "Pokémon while he was gone?$"

TwinLeafTownBottomLeftHouse_EventScript_Little_Girl_Text_0:
	.string "Listen, listen, {PLAYER}.\p"
	.string "I want a cute Pokémon!$"
