Jubilife_City_South_House_1F_MapScripts::
	.byte 0


Jubilife_City_South_House_1F_EventScripts_Girl::
	msgbox Jubilife_City_South_House_1F_EventScripts_Girl_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_1F_EventScripts_Pachirisu::
	msgbox Jubilife_City_South_House_1F_EventScripts_Pachirisu_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_1F_EventScripts_Ace_Girl::
	msgbox Jubilife_City_South_House_1F_EventScripts_Ace_Girl_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_1F_EventScripts_Books::
	msgbox Jubilife_City_South_House_1F_EventScripts_Books_Text, MSGBOX_SIGN
	end


Jubilife_City_South_House_1F_EventScripts_Girl_Text::
	.string "Hello there, Trainer!\p"
	.string "If you get stumped and don’t know\n"
	.string "what to do...\p"
	.string "Talk to people!\n"
	.string "Talk to everyone you see!\p"
	.string "Go places!\n"
	.string "Go wherever you can!\p"
	.string "You’ll find many new places by\n"
	.string "doing just that.$"

Jubilife_City_South_House_1F_EventScripts_Pachirisu_Text::
	.string "PACHIRISU: Kukkuuh!$"

Jubilife_City_South_House_1F_EventScripts_Ace_Girl_Text::
	.string "Pokémon are wonderful, deeply\n"
	.string "mysterious creatures.\p"
	.string "But to Trainers, the key thing is to do\n"
	.string "battle with their Pokémon.\p"
	.string "That’s what it boils down to.$"

Jubilife_City_South_House_1F_EventScripts_Books_Text::
	.string "It's chock-full of Pokémon books and\n"
	.string "photo collections.$"
