Jubilife_City_Condominiums_2F_MapScripts::
	.byte 0


Jubilife_City_Condominiums_2F_EvenetScripts_Man::
	msgbox Jubilife_City_Condominiums_2F_EvenetScripts_Man_Text, MSGBOX_NPC
	end


Jubilife_City_Condominiums_2F_EvenetScripts_Bug_Catcher::
	msgbox Jubilife_City_Condominiums_2F_EvenetScripts_Bug_Catcher_Text, MSGBOX_NPC
	end


Jubilife_City_Condominiums_2F_EvenetScripts_Man_Text::
	.string "Did you buy some Heal Balls at the\n"
	.string "Poké Mart?\p"
	.string "A Heal Ball completely heals the\n"
	.string "Pokémon it captures on the spot.\p"
	.string "That means you can catch a Pokémon\n"
	.string "and have it battle-ready right away.\p"
	.string "Of course, if your team has six\n"
	.string "Pokémon in it, it won’t do any good.$"

Jubilife_City_Condominiums_2F_EvenetScripts_Bug_Catcher_Text::
	.string "I like how Pokémon can use attacks.\n"
	.string "That makes things fun and different.\p"
	.string "Sometimes, when they get stronger,\n"
	.string "Pokémon learn new moves.\p"
	.string "That keeps things fresh and fun when\n"
	.string "using moves.$"
