OreburghCityBottomBigHouse1F_MapScripts::
	.byte 0


OreburghCityBottomBigHouse1F_EventScript_Woman::
	msgbox OreburghCityBottomBigHouse1F_EventScript_Woman_Text_0, MSGBOX_NPC
	end


OreburghCityBottomBigHouse1F_EventScript_Old_Man::
	msgbox OreburghCityBottomBigHouse1F_EventScript_Old_Man_Text_0, MSGBOX_NPC
	end


OreburghCityBottomBigHouse1F_EventScript_Hiker::
	msgbox OreburghCityBottomBigHouse1F_EventScript_Hiker_Text_0, MSGBOX_NPC
	end


OreburghCityBottomBigHouse1F_EventScript_Books::
	msgbox OreburghCityBottomBigHouse1F_EventScript_Books_Text_0, MSGBOX_DEFAULT
	end


OreburghCityBottomBigHouse1F_EventScript_Woman_Text_0:
	.string "You remind me so much of the time\n"
	.string "I got my first Pokémon.$"

OreburghCityBottomBigHouse1F_EventScript_Old_Man_Text_0:
	.string "Hiya! Your Pokémon could use some\n"
	.string "toughening up.\p"
	.string "Why not try training in\n"
	.string "the Oreburgh Mine?$"

OreburghCityBottomBigHouse1F_EventScript_Hiker_Text_0:
	.string "I always have a rotten time trying\n"
	.string "to decide which moves my Pokémon\l"
	.string "should learn.$"

OreburghCityBottomBigHouse1F_EventScript_Books_Text_0:
	.string "It's chock-full of Pokémon books and\n"
	.string "photo collections.$"
