OreburghCitySouthHouse_MapScripts::
	.byte 0


OreburghCitySouthHouse_EventScript_Worker::
	msgbox OreburghCitySouthHouse_EventScript_Worker_Text_0, MSGBOX_NPC
	end


OreburghCitySouthHouse_EventScript_Worker_Text_0:
	.string "You're taking a tour of our coal mine?\p"
	.string "Wonderful!\n"
	.string "That's excellent of you.\p"
	.string "It's always good to learn about new\n"
	.string "things and broaden your horizons!$"
