OreburghCityRightBigHouse1F_MapScripts::
	.byte 0


OreburghCityRightBigHouse1F_EventScript_Boy::
	msgbox OreburghCityRightBigHouse1F_EventScript_Boy_Text_0, MSGBOX_NPC
	end


OreburghCityRightBigHouse1F_EventScript_Girl::
	end


OreburghCityRightBigHouse1F_EventScript_Old_Lady::
	msgbox OreburghCityRightBigHouse1F_EventScript_Old_Lady_Text_0, MSGBOX_NPC
	end


OreburghCityRightBigHouse1F_EventScript_Books::
	msgbox OreburghCityRightBigHouse1F_EventScript_Books_Text_0, MSGBOX_DEFAULT
	end


OreburghCityRightBigHouse1F_EventScript_Boy_Text_0:
	.string "When you trade a Pokémon, the item it's\n"
	.string "holding is traded as well.\p"
	.string "That's pretty cool, huh?\p"
	.string "It means you can send an item as a gift\n"
	.string "along with your Pokémon in a trade!$"

OreburghCityRightBigHouse1F_EventScript_Old_Lady_Text_0:
	.string "A Pokémon obtained in a trade grows\n"
	.string "quickly.\p"
	.string "But if a Pokémon grows too much, it may\n"
	.string "ignore the Trainer.\p"
	.string "Of course, it won't matter if you have\n"
	.string "lots of Gym Badges.$"

OreburghCityRightBigHouse1F_EventScript_Books_Text_0:
	.string "It's chock-full of Pokémon books and\n"
	.string "photo collections.$"
