OreburghCityRightBigHouse2F_MapScripts::
	.byte 0


OreburghCityRightBigHouse2F_EventScript_Man::
	msgbox OreburghCityRightBigHouse2F_EventScript_Man_Text_0, MSGBOX_NPC
	end


OreburghCityRightBigHouse2F_EventScript_Woman::
	msgbox OreburghCityRightBigHouse2F_EventScript_Woman_Text_0, MSGBOX_NPC
	end


OreburghCityRightBigHouse2F_EventScript_Fat_Man::
	msgbox OreburghCityRightBigHouse2F_EventScript_Fat_Man_Text_0, MSGBOX_NPC
	end


OreburghCityRightBigHouse2F_EventScript_Man_Text_0:
	.string "All Pokémon have a special power\n"
	.string "called an ability.$"

OreburghCityRightBigHouse2F_EventScript_Woman_Text_0:
	.string "My favorite Pokémon ability is my\n"
	.string "Pachirisu's Pickup.\p"
	.string "My darling picks up a lot of dropped\n"
	.string "items without me noticing!$"

OreburghCityRightBigHouse2F_EventScript_Fat_Man_Text_0:
	.string "The view is good from the second floor,\n"
	.string "but it's a pain going outside.\p"
	.string "If you don't mind, how about showing me\n"
	.string "a Pokémon called Geodude?$"
