Jubilife_City_South_House_2F_MapScripts::
	.byte 0


Jubilife_City_South_House_2F_EventScripts_Youngster::
	msgbox Jubilife_City_South_House_2F_EventScripts_Youngster_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_2F_EventScripts_Woman::
	msgbox Jubilife_City_South_House_2F_EventScripts_Woman_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_2F_EventScripts_Girl::
	msgbox Jubilife_City_South_House_2F_EventScripts_Girl_Text, MSGBOX_NPC
	end


Jubilife_City_South_House_2F_EventScripts_Youngster_Text::
	.string "Did you know?\p"
	.string "Some kinds of Pokémon evolve when\n"
	.string "they get stronger from battling!\p"
	.string "When they evolve, they can take on\n"
	.string "completely different forms!$"

Jubilife_City_South_House_2F_EventScripts_Woman_Text::
	.string "Evolution makes Pokémon just that\n"
	.string "much more fascinating.\p"
	.string "The mysteries of evolution... Can that\n"
	.string "dandy Prof. Rowan unravel them?$"

Jubilife_City_South_House_2F_EventScripts_Girl_Text::
	.string "Didn’t Prof. Rowan conduct research\n"
	.string "with Prof. Oak of the Kanto region?$"
